language: node_js
node_js:
  - "0.12"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - build-essential
      - g++-4.8
env:
  - CXX=g++-4.8
sudo: false

script: "npm test"